name: ci_cd
on:
  push:
    tags:        
      - v*
env:
  UPLOAD_KEY: ${{secrets.UPLOAD_KEY}}
  APPID: ${{secrets.APPID}}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
    
    - name: Cache node modules
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        # 缓存命中
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        # 存储key
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install Dependency
      run: |
        npm install

    - name: Deploy To Wechat Miniprogram Platform
      run: |
          echo "$APPID $GITHUB_REF_NAME $GITHUB_REF_NAME版本"
          echo "$UPLOAD_KEY" > ./scripts/privatekey.key
          node ./scripts/ci.js --appid $APPID --version $GITHUB_REF_NAME --desc "$GITHUB_REF_NAME版本"
    
